name: Check HTML

on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  lint_markdown:
    name: Lint HTML code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          cache: pip
          python-version: '3.14'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build website
        run: |
          python src/rss_to_html.py
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      - name: Install html-validate
        run: |
          npm install -g html-validate
      - name: Run html-validate
        run: |
          set -e
          for file in output/*.html; do
            if [ "${file}" = "output/security.html" ]; then
              html-validate  \
                --preset recommended \
                --rule no-trailing-whitespace:warn \
                output/security.html
            else
              html-validate  "${file}"
            fi
          done
