name: Check Markdown files

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint_markdown:
    name: Lint Markdown code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      - name: Install markdownlint-cli
        run: |
          npm install -g markdownlint-cli
      - name: Run markdownlint
        run: |
          markdownlint "**/*.md" \
            --ignore "node_modules/**/*" \
            --ignore "myenv/**/*"

  spell_check:
    name: Spell check Markdown files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      - name: Install cspell
        run: |
          npm install -g cspell
      - name: Run cspell
        run: |
          cspell "**/*.md" \
            --config config/cspell.json \
            --exclude "node_modules/**/*" \
            --exclude "myenv/**/*"
