name: Build and Deploy Website

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy_website:
    name: Deploy from artifact
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download output artifact
        id: download_artifact
        # continue-on-error: true
        uses: actions/download-artifact@v7
        with:
          name: website_build_output
          path: output
      # - name: If artifact download fails, build output
      #   if: steps.download_artifact.outcome == 'failure'
      #   uses: ./.github/workflows/website_build.yaml
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: gh-pages
